### ISSUE TITLE
Merge With go-plus

### ISSUE THREAD

**Issue by joefitzgerald** [zheng1/go-hyperclick#4]
@zheng1 thank you for creating such a useful package. I love go-hyperclick and want to include the functionality in go-plus. As part of this I would like to attribute this functionality to you and give you the ability to maintain the functionality.

Is this something you would be open to?

**Comment by joefitzgerald** [comment]
See also: https://github.com/joefitzgerald/go-plus/pull/503

**Comment by zheng1** [comment]
Yes, I will.
